server {
	listen 443 ssl;
	ssl_certificate		/etc/nginx/cert.pem;
	ssl_certificate_key /etc/nginx/key.pem;

    root /usr/share/nginx/html;
    index index.html;

    # React Router — toutes les routes inconnues → index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy API vers le backend
    location /api/ {
        proxy_pass https://backend:3000/;
		proxy_ssl_verify off;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }

    # Proxy Socket.io vers le backend
    location /socket.io/ {
        proxy_pass https://backend:3000;
		proxy_ssl_verify off;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}